# Generated by Django 3.0.2 on 2020-01-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20)),
                ('place_of_birth', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='images')),
                ('slug', models.SlugField()),
            ],
        ),
    ]
