# Generated by Django 3.0.2 on 2020-01-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=20),
        ),
    ]
