# Generated by Django 3.0.2 on 2020-01-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0002_auto_20200118_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='biography',
            name='title',
            field=models.CharField(default='danindra biography', max_length=100),
            preserve_default=False,
        ),
    ]
