# Generated by Django 3.0.2 on 2020-01-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0003_biography_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='male', max_length=20),
        ),
    ]
